import { useMemo, useState } from 'react';
import { FileText, Download, Loader2, CheckCircle } from 'lucide-react';
import { HeroBudi } from './MascotSplash';
import './AgreementDraft.css';

const DEFAULT_TERMS =
  'Utilities (electricity, water, internet) are shouldered by the tenant unless otherwise stated.';

const AgreementDraft = ({ session }) => {
  const today = new Date().toISOString().slice(0, 10);
  const [form, setForm] = useState({
    tenantName: '',
    landlordName: session?.user?.user_metadata?.full_name || session?.user?.email || '',
    property: '',
    address: '',
    rent: '',
    advance: '1',
    deposit: '2',
    startDate: today,
    duration: '6',
    terms: DEFAULT_TERMS,
  });
  const [generating, setGenerating] = useState(false);
  const [done, setDone] = useState(false);

  const set = (field, value) => setForm(prev => ({ ...prev, [field]: value }));

  const clauses = useMemo(() => {
    const peso = (v) => (v ? `₱${Number(v).toLocaleString()}` : '________');
    const list = [
      `The tenant agrees to pay a monthly rent of ${peso(form.rent)}, payable on or before each due date.`,
      `An advance payment of ${form.advance || '___'} month(s) and a security deposit of ${form.deposit || '___'} month(s) shall be settled upon move-in.`,
      `The lease shall commence on ${form.startDate || '________'} and shall remain in effect for ${form.duration || '___'} month(s), unless renewed by both parties.`,
      'The tenant shall not sublet or assign the property to a third party without the written consent of the landlord.',
      'The landlord shall keep the property in good and livable condition throughout the duration of the lease.',
      'Either party may terminate this agreement by giving at least thirty (30) days written notice.',
      `Special terms: ${form.terms || 'None'}`,
    ];
    return list;
  }, [form]);

  const generatePDF = async () => {
    setGenerating(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'pt', format: 'a4' });
      const PW = doc.internal.pageSize.getWidth();
      const PH = doc.internal.pageSize.getHeight();
      const M = 54;
      const innerW = PW - M * 2;
      const navy = [0, 51, 102];
      const gold = [245, 158, 11];
      const gray = [71, 85, 105];
      const ink = [30, 41, 59];
      // Standard PDF fonts walang peso sign
      const t = (v) => String(v ?? '').replace(/₱/g, 'PHP ').replace(/[—–]/g, '-');

      const drawFooter = () => {
        doc.setFillColor(...navy);
        doc.rect(0, PH - 36, PW, 36, 'F');
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(255, 255, 255);
        doc.text('Generated by BudgetRentPH - Keep this draft for your records.', PW / 2, PH - 14, { align: 'center' });
      };
      const bottom = PH - 60;
      let y = 0;
      const ensure = (h) => {
        if (y + h > bottom) {
          drawFooter();
          doc.addPage();
          y = M;
        }
      };

      // Header
      doc.setFillColor(...navy);
      doc.rect(0, 0, PW, 86, 'F');
      doc.setFillColor(...gold);
      doc.rect(0, 86, PW, 4, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(26);
      doc.setTextColor(255, 255, 255);
      doc.text('Budget', M, 50);
      const w1 = doc.getTextWidth('Budget');
      doc.setTextColor(...gold);
      doc.text('Rent', M + w1, 50);
      const w2 = doc.getTextWidth('Rent');
      doc.setTextColor(255, 255, 255);
      doc.text('PH', M + w1 + w2, 50);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9.5);
      doc.text('Affordable rentals, honest deals.', M, 68);
      doc.setFont('helvetica', 'bold');
      doc.text(new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' }), PW - M, 50, { align: 'right' });

      // Title
      y = 130;
      doc.setFontSize(18);
      doc.setTextColor(...navy);
      doc.text('TENANCY AGREEMENT DRAFT', PW / 2, y, { align: 'center' });
      y += 18;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(...gray);
      doc.text('Draft only - review and sign with both parties before it becomes final.', PW / 2, y, { align: 'center' });
      y += 26;

      // Details
      const rows = [
        ['Tenant Name', form.tenantName || '-'],
        ['Landlord Name', form.landlordName || '-'],
        ['Property / Unit', form.property || '-'],
        ['Address', form.address || '-'],
        ['Monthly Rent', form.rent ? `₱${Number(form.rent).toLocaleString()}` : '-'],
        ['Advance / Deposit', `${form.advance || 0} mos / ${form.deposit || 0} mos`],
        ['Lease Start', form.startDate || '-'],
        ['Duration', `${form.duration || 0} month(s)`],
      ];
      rows.forEach(([label, value]) => {
        const lines = doc.splitTextToSize(t(value), innerW - 150);
        const h = Math.max(22, lines.length * 13 + 9);
        ensure(h);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(...navy);
        doc.text(label, M, y + 13);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10.5);
        doc.setTextColor(...ink);
        doc.text(lines, M + 150, y + 13);
        doc.setDrawColor(226, 232, 240);
        doc.setLineWidth(0.6);
        doc.line(M, y + h - 3, PW - M, y + h - 3);
        y += h;
      });

      // Clauses
      y += 24;
      ensure(40);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(...navy);
      doc.text('Terms & Conditions', M, y);
      doc.setFillColor(...gold);
      doc.rect(M, y + 6, 54, 2.5, 'F');
      y += 26;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10.5);
      doc.setTextColor(51, 65, 85);
      clauses.forEach((c, i) => {
        const lines = doc.splitTextToSize(t(`${i + 1}. ${c}`), innerW - 8);
        lines.forEach((line, li) => {
          ensure(16);
          doc.text(line, M + (li ? 12 : 0), y);
          y += 15;
        });
        y += 4;
      });

      // Note
      y += 8;
      const noteLines = doc.splitTextToSize('This draft was generated via BudgetRentPH and is not a legally binding contract until signed by both parties. It is not legal advice.', innerW - 28);
      const noteH = noteLines.length * 13 + 18;
      ensure(noteH);
      doc.setFillColor(254, 243, 220);
      doc.setDrawColor(240, 190, 100);
      doc.roundedRect(M, y, innerW, noteH, 6, 6, 'FD');
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9.5);
      doc.setTextColor(...navy);
      doc.text(noteLines, M + 14, y + 17);
      y += noteH + 36;

      // Signatures
      ensure(110);
      const colW = (innerW - 50) / 2;
      [['Tenant Signature', form.tenantName], ['Landlord Signature', form.landlordName]].forEach(([label, name], i) => {
        const x = M + i * (colW + 50);
        doc.setDrawColor(148, 163, 184);
        doc.setLineWidth(1);
        doc.line(x, y + 36, x + colW, y + 36);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(...navy);
        doc.text(label, x, y + 52);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(...gray);
        doc.text(doc.splitTextToSize(t(name || '________________'), colW), x, y + 66);
        doc.text('Date: ____________', x, y + 80);
      });

      drawFooter();
      const safeName = (form.tenantName || 'tenant').replace(/[^a-z0-9]+/gi, '-').toLowerCase();
      doc.save(`agreement-draft-${safeName}-${today}.pdf`);
      setDone(true);
      setTimeout(() => setDone(false), 4000);
    } catch (err) {
      console.error('PDF generation failed:', err);
      alert('Failed to generate PDF: ' + err.message);
    } finally {
      setGenerating(false);
    }
  };

  const input = (field, label, type = 'text', placeholder = '') => (
    <div className="agr-field">
      <label>{label}</label>
      <input
        type={type}
        value={form[field]}
        placeholder={placeholder}
        onChange={e => set(field, e.target.value)}
      />
    </div>
  );

  return (
    <div className="page-section animate-fade-in">
      <header className="hero branding-hero">
        <HeroBudi message="Punan ang detalye at gagawa ako ng kontrata para sa tenant mo." />
        <div className="hero-content">
          <span className="branding-kicker">Landlord Tools</span>
          <h2>Agreement Draft</h2>
          <p>Gumawa ng kontrata sa iyong tenant at i-download bilang PDF</p>
        </div>
      </header>

      <main className="agr-container">
        <div className="agr-layout">
          {/* FORM */}
          <section className="agr-form-card">
            <div className="agr-card-title">
              <FileText size={18} />
              <h3>Contract Details</h3>
            </div>

            <div className="agr-grid">
              {input('tenantName', 'Tenant Name', 'text', 'Juan Dela Cruz')}
              {input('landlordName', 'Landlord Name', 'text', 'Your full name')}
              {input('property', 'Property / Unit', 'text', 'Room 101, Budget Dorm')}
              {input('address', 'Address', 'text', 'Brgy. Poblacion, City')}
              {input('rent', 'Monthly Rent (₱)', 'number', '5000')}
              {input('duration', 'Duration (months)', 'number', '6')}
              <div className="agr-field">
                <label>Advance (months)</label>
                <select value={form.advance} onChange={e => set('advance', e.target.value)}>
                  {[0, 1, 2, 3].map(n => <option key={n} value={n}>{n}</option>)}
                </select>
              </div>
              <div className="agr-field">
                <label>Security Deposit (months)</label>
                <select value={form.deposit} onChange={e => set('deposit', e.target.value)}>
                  {[0, 1, 2, 3].map(n => <option key={n} value={n}>{n}</option>)}
                </select>
              </div>
              {input('startDate', 'Lease Start', 'date')}
            </div>

            <div className="agr-field">
              <label>Special Terms</label>
              <textarea
                rows={3}
                value={form.terms}
                onChange={e => set('terms', e.target.value)}
                placeholder="Kahit anong dagdag na patakaran..."
              />
            </div>

            <button
              className="agr-generate-btn"
              onClick={generatePDF}
              disabled={generating || !form.tenantName}
              title={!form.tenantName ? 'Ilagay muna ang tenant name' : 'Generate PDF'}
            >
              {generating ? <Loader2 size={18} className="animate-spin" /> : <Download size={18} />}
              {generating ? 'Generating...' : 'Generate PDF Draft'}
            </button>

            {done && (
              <div className="agr-success">
                <CheckCircle size={16} /> Na-download na ang agreement PDF sa iyong device.
              </div>
            )}
            {!form.tenantName && (
              <p className="agr-hint">Ilagay ang tenant name para ma-activate ang generation.</p>
            )}
          </section>

          {/* PREVIEW */}
          <section className="agr-preview-wrap">
            <div className="agr-card-title">
              <FileText size={18} />
              <h3>Preview</h3>
            </div>
            <div className="agr-paper">
              <div className="agr-paper-head">
                <span className="agr-brand">Budget<span>Rent</span>PH</span>
                <span className="agr-date">{today}</span>
              </div>
              <div className="agr-gold-bar" />
              <h4>TENANCY AGREEMENT DRAFT</h4>
              <p className="agr-sub">Draft only — review and sign with both parties before it becomes final.</p>

              <dl className="agr-info">
                <div><dt>Tenant Name</dt><dd>{form.tenantName || '—'}</dd></div>
                <div><dt>Landlord Name</dt><dd>{form.landlordName || '—'}</dd></div>
                <div><dt>Property / Unit</dt><dd>{form.property || '—'}</dd></div>
                <div><dt>Address</dt><dd>{form.address || '—'}</dd></div>
                <div><dt>Monthly Rent</dt><dd>{form.rent ? `₱${Number(form.rent).toLocaleString()}` : '—'}</dd></div>
                <div><dt>Advance / Deposit</dt><dd>{form.advance} mos / {form.deposit} mos</dd></div>
                <div><dt>Lease Start</dt><dd>{form.startDate || '—'}</dd></div>
                <div><dt>Duration</dt><dd>{form.duration} month(s)</dd></div>
              </dl>

              <h5>Terms & Conditions</h5>
              <ol className="agr-clauses">
                {clauses.map((c, i) => <li key={i}>{c}</li>)}
              </ol>

              <div className="agr-note">
                This draft was generated via BudgetRentPH and is not a legally binding contract
                until signed by both parties.
              </div>

              <div className="agr-sign-row">
                <div className="agr-sign">
                  <span className="agr-sign-line" />
                  <strong>Tenant Signature</strong>
                  <em>{form.tenantName || '________________'} • Date: __________</em>
                </div>
                <div className="agr-sign">
                  <span className="agr-sign-line" />
                  <strong>Landlord Signature</strong>
                  <em>{form.landlordName || '________________'} • Date: __________</em>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
};

export default AgreementDraft;
